import json

from rdkit import Chem, RDLogger
from rdkit.Chem import rdChemReactions

logger = RDLogger.logger()
logger.setLevel(RDLogger.CRITICAL)


class SmilesError(ValueError): ...


class ReactantError(ValueError): ...


class ReactionError(ValueError): ...


class ProductsError(ValueError): ...


def validate(response: str) -> None:
    try:
        data = json.loads(response)
    except json.JSONDecodeError as e:
        raise e

    # Validate Building Blocks
    blocks = []
    building_blocks = data["building_blocks"]
    for bb in building_blocks:
        if bb.startswith("<bb>"):
            bb = bb[4:]
        if bb.endswith("</bb>"):
            bb = bb[:-5]
        mol = Chem.MolFromSmiles(bb)
        if mol is None:
            raise SmilesError("Invalid building block SMILES")
        blocks.append(mol)

    # Validate Reactions
    reactions = data["reactions"]
    for reaction in reactions:
        rxn_template = reaction["reaction_template"]
        if rxn_template.startswith("<rxn>"):
            rxn_template = rxn_template[5:]
        if rxn_template.endswith("</rxn>"):
            rxn_template = rxn_template[:-6]

        # Load reaction
        rxn = rdChemReactions.ReactionFromSmarts(rxn_template)
        rxn.Initialize()

        # Load reactants and products
        reactants = [Chem.MolFromSmiles(m) for m in reaction["reactants"] if m != ""]
        product = Chem.MolFromSmiles(reaction["product"])
        if any(m is None for m in reactants) or product is None:
            # if either reactants or product smiles are malformed SMILES
            raise SmilesError("Invalid smiles")

        # Check that the reactants provided match the reactants of the template
        for reactant in reactants:
            reactant: Chem.Mol
            for template in rxn.GetReactants():
                match = reactant.HasSubstructMatch(template)
                if match:
                    break
            else:
                raise ReactantError("Provided reactants don't match template")

        # Run the reaction, if it generates no products raise reaction error
        products = [
            Chem.MolToSmiles(m, canonical=True, ignoreAtomMapNumbers=True)
            for p in rxn.RunReactants(reactants)
            for m in p
        ]
        if not products:
            raise ReactionError("Reaction on provided reactants produced no products")

        # Check that the product generated by the reactants and products gives
        # the expected product
        product_smiles = Chem.CanonSmiles(
            Chem.MolToSmiles(product, canonical=True, ignoreAtomMapNumbers=True)
        )
        for prod in products:
            if product_smiles == Chem.CanonSmiles(prod):
                break
        else:
            # print("PRODUCT", product_smiles)
            # print("REACTANTS", [Chem.MolToSmiles(m) for m in reactants])
            # print("PRODUCTS", products)
            # print()
            raise ProductsError("Expected product not in provided products")
