import json
from pathlib import Path

import polars as pl
from rdkit import Chem, RDLogger
from rdkit.Chem import rdChemReactions

logger = RDLogger.logger()
logger.setLevel(RDLogger.CRITICAL)


class SmilesError(ValueError): ...


class ReactantError(ValueError): ...


class ReactionError(ValueError): ...


class ProductsError(ValueError): ...


def validate(response: str) -> None:
    try:
        data = json.loads(response)
    except json.JSONDecodeError as e:
        raise e

    # Validate Building Blocks
    blocks = []
    building_blocks = data["building_blocks"]
    for bb in building_blocks:
        if bb.startswith("<bb>"):
            bb = bb[4:]
        if bb.endswith("</bb>"):
            bb = bb[:-5]
        mol = Chem.MolFromSmiles(bb)
        if mol is None:
            raise SmilesError("Invalid building block SMILES")
        blocks.append(mol)

    # Validate Reactions
    reactions = data["reactions"]
    for reaction in reactions:
        rxn_template = reaction["reaction_template"]
        if rxn_template.startswith("<rxn>"):
            rxn_template = rxn_template[5:]
        if rxn_template.endswith("</rxn>"):
            rxn_template = rxn_template[:-6]

        # Load reaction
        rxn = rdChemReactions.ReactionFromSmarts(rxn_template)
        rxn.Initialize()

        # Load reactants and products
        reactants = [Chem.MolFromSmiles(m) for m in reaction["reactants"] if m != ""]
        product = Chem.MolFromSmiles(reaction["product"])
        if any(m is None for m in reactants) or product is None:
            # if either reactants or product smiles are malformed SMILES
            raise SmilesError("Invalid smiles")

        # Check that the reactants provided match the reactants of the template
        for reactant in reactants:
            reactant: Chem.Mol
            for template in rxn.GetReactants():
                match = reactant.HasSubstructMatch(template)
                if match:
                    break
            else:
                raise ReactantError("Provided reactants don't match template")

        # Run the reaction, if it generates no products raise reaction error
        products = [
            Chem.MolToSmiles(m, canonical=True, ignoreAtomMapNumbers=True)
            for p in rxn.RunReactants(reactants)
            for m in p
        ]
        if not products:
            raise ReactionError("Reaction on provided reactants produced no products")

        # Check that the product generated by the reactants and products gives
        # the expected product
        product_smiles = Chem.CanonSmiles(
            Chem.MolToSmiles(product, canonical=True, ignoreAtomMapNumbers=True)
        )
        for prod in products:
            if product_smiles == Chem.CanonSmiles(prod):
                break
        else:
            # print("PRODUCT", product_smiles)
            # print("REACTANTS", [Chem.MolToSmiles(m) for m in reactants])
            # print("PRODUCTS", products)
            # print()
            raise ProductsError("Expected product not in provided products")


def main(file: Path, output_dir: Path, sampling: str = "all"):
    df = pl.read_csv(file.resolve())
    if sampling == "all":
        pass
    else:
        df = df.filter(pl.col("sampling_params") == sampling)

    valid = []
    failed = []

    ntotal: int = df.height
    errors = {
        "json": 0,
        "smiles": 0,
        "reactant": 0,
        "reaction": 0,
        "product": 0,
        "other": 0,
    }
    for row in df.rows(named=True):
        success = False
        try:
            validate(row["response"])
            success = True
        except json.JSONDecodeError:
            errors["json"] += 1
        except SmilesError:
            errors["smiles"] += 1
        except ReactantError:
            errors["reactant"] += 1
        except ReactionError:
            errors["reaction"] += 1
        except ProductsError:
            errors["product"] += 1
        except Exception:
            errors["other"] += 1

        if success:
            valid.append(row)
        else:
            failed.append(row)

    total_errors = sum(errors.values())
    print(
        f"Valid percentatge: {ntotal - total_errors}/{ntotal}, {(ntotal - total_errors) / ntotal * 100:3.2f}%"
    )
    for err, val in errors.items():
        print(
            f"{err}: {val}/{total_errors}, {val / total_errors * 100:3.2f}% of errors"
        )

    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    fail_df = pl.DataFrame(failed)
    fail_df.write_csv(output / "synllama-raw-failed.csv")
    valid_df = pl.DataFrame(valid)
    valid_df.write_csv(output / "synllama-raw-valid.csv")


if __name__ == "__main__":
    root = Path(__file__).parent
    main(root / "synllama-raw-output.csv", root, sampling="all")
